functionality:
  name: cat_format
  description: |
    cat a file and wrap it in a fenced code block with
    an optional format identifier.
  arguments:
    - name: "input"
      type: file
      required: true
      must_exist: true
      description: "Input file"
    - name: "--format"
      alternatives: [ "-f" ]
      type: string
      required: true
      description: "Format for code block"
  resources:
    - type: bash_script
      path: script.sh
platforms:
  - type: native
