---
author: Data Intuitive
date: Tuesday - January 26, 2021
mainfont: Roboto Condensed
monofont: Source Code Pro
monofontoptions: Scale=0.7
monobackgroundcolor: lightgrey
title: Viash Workshop 1 - Running the pipeline
---

```{r setup, include = FALSE}
# set default chunk options
knitr::opts_chunk$set(
  echo = TRUE,
  comment = "",
  collapse = TRUE,
  prompt = TRUE,
  cache = T
  # engine.opts = list(bash = "-l")
)
```

# Introduction

In this section, we demonstrate how to run the full pipeline for the Civilization postgame generation.

# Building the namespace

Let's build the namespace from the `src` directory in the root of this project/repository again, so we keep this directory self-contained:

```{sh}
viash ns build \
  -n civ6_save_renderer \
  -s ../src \
  -p docker
```

The result is stored under `target/docker` because we chose to only build the `docker` platform executables.

We have to run the _setup_ for the containers that are not just available on Docker Hub. This can be done in one go by using the following CLI:

```sh
cd ..
viash ns build \
  -n civ6_save_renderer \
  -s ../src \
  -p docker
```

Or, we can run them one-by-one.

# A pipeline script

A small dataset with only a few steps from a game are stored under `../data/`. We will use that as a source for the pipeline. Furthermore, we'll _eat our own dogfoot_ and create a [viash] component for the pipeline code itself:

```{sh results="asis", echo = F}
../scripts/cat_format src/civ6_save_renderer/pipeline/config.vsh.yaml
```

With the following script:

```{sh results="asis", echo = F}
../scripts/cat_format src/civ6_save_renderer/pipeline/script.sh
```

A few remarks are in place here:

>> TODO

Build the `pipeline` component:

```{sh}
viash ns build -p native
```

# Running the pipeline

Make sure you have run the required `--setup`'s. Then:

```{sh}
target/native/civ6_save_renderer/pipeline/pipeline \
  -i ../data \
  -o output.webm
```




[viash]: https://github.com/data-intuitive/viash
