functionality:
  name: combine_plots
  namespace: civ6_save_renderer
  description: Combine multiple images into a movie using ffmpeg.
  version: "1.0"
  authors:
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [maintainer, author]
      props: {github: rcannood, orcid: 0000-0003-3641-729X}
  arguments:
    - name: "--input"
      alternatives: [-i]
      type: file
      required: true
      default: "plot1.png:plot2.png"
      must_exist: true
      multiple: true
      description: A list of images.
    - name: "--output"
      alternatives: [-o]
      type: file
      required: true
      default: "output.webm"
      direction: output
      description: A path to output the movie to.
    - name: "--framerate"
      alternatives: [-f]
      type: integer
      default: 4
      description: Number of frames per second.
  resources:
    - type: bash_script
      path: script.sh
  tests:
    - type: bash_script
      path: test/run_test.sh
    - path: https://github.com/hplgit/animate/raw/master/doc/src/animate/src-animate/testfiles/frames/frame_0000.png
    - path: https://github.com/hplgit/animate/raw/master/doc/src/animate/src-animate/testfiles/frames/frame_0001.png
    - path: https://github.com/hplgit/animate/raw/master/doc/src/animate/src-animate/testfiles/frames/frame_0002.png
    - path: https://github.com/hplgit/animate/raw/master/doc/src/animate/src-animate/testfiles/frames/frame_0003.png
    - path: https://github.com/hplgit/animate/raw/master/doc/src/animate/src-animate/testfiles/frames/frame_0004.png
    - path: https://github.com/hplgit/animate/raw/master/doc/src/animate/src-animate/testfiles/frames/frame_0005.png
    - path: https://github.com/hplgit/animate/raw/master/doc/src/animate/src-animate/testfiles/frames/frame_0006.png
    - path: https://github.com/hplgit/animate/raw/master/doc/src/animate/src-animate/testfiles/frames/frame_0007.png
    - path: https://github.com/hplgit/animate/raw/master/doc/src/animate/src-animate/testfiles/frames/frame_0008.png
platforms:
  - type: docker
    image: jrottenberg/ffmpeg
  - type: nextflow
    image: jrottenberg/ffmpeg
    publish: true
  - type: native
