name: viash ns test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  viash-ns-test:
    runs-on: ${{ matrix.config.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    
    strategy:
      fail-fast: false
      matrix:
        config: 
        - {name: 'main', os: ubuntu-latest }

    steps:
    - uses: actions/checkout@v2
        
    - name: Install viash
      run: |
        mkdir -p "$HOME/.local/bin"
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        wget https://github.com/data-intuitive/viash/releases/download/v0.3.2/viash -qO "$HOME/.local/bin/viash"
        chmod +x "$HOME/.local/bin/viash"
        
    - name: Verify that viash is on path
      run: | 
        viash -h

    - name: Run tests
      run: |
        viash ns test -p docker
        
    - name: Upload check results on fail
      if: failure()
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.config.name }}_results
        path: check
